backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
collections:
  - name: "boletas"
    label: "Boletas"
    files:
      - name: "listado"
        label: "Listado de Boletas"
        file: "data/boletas.json"
        fields:
          - label: "Boletas"
            name: "boletas"
            widget: list
            fields:
              - { label: "Número", name: "numero", widget: number }
              - { label: "Estado", name: "estado", widget: select, options: [libre, pendiente, pagado] }
              - { label: "Nombre", name: "nombre", widget: string, required: false }
              - { label: "Teléfono", name: "telefono", widget: string, required: false }